[package]
name = "translate"
version = "0.1.0"
authors = ["David"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.0-rc.2"
google-translate2 = "1.0.14+20170525"